[package]
name = "instancing"
version = "0.1.0"
edition = "2024"

# 告诉cargo允许项目构建一个本地的Rust静态库和一个C/C++兼容库。需要rlib在桌面环境之中运行wgpu，并需要cdylib来构建在
# 浏览器之中运行的WASM
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
cgmath = { workspace = true }
env_logger = { workspace = true }
image = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# 配置 panic! 宏以将错误发送到 javascript 控制台。如果没有这个，当遇到程序崩溃时，你就会对导致崩溃的原因一无所知
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
wgpu = { workspace = true, features = ["webgl"] }
